DM-39813-main: Add 25.0.0 release notes
lsst/pipelines_lsst_io pull request #261
Opened 2023-07-21 21:25 UTC by mwittgen

2023-07-21 23:58 UTC, mwittgen commented
Build: https://pipelines.lsst.io/v/tickets-DM-39813-main/index.html

2023-07-24 19:17 UTC, jonathansick requested changes

2023-07-24 19:17 UTC, jonathansick commented on releases/v25_0_0.rst
> +--------------
Remember to add a blank line after section underlines (check all sections).

2023-07-24 19:17 UTC, jonathansick commented on releases/v25_0_0.rst
> +If you have questions or comments about this release, visit our `community forum <https://community.lsst.org>`_ for advice.
```suggestion
If you have questions or comments about this release, visit our `Community forum <https://community.lsst.org>`_ for advice.
```

2023-07-24 19:17 UTC, jonathansick commented on releases/v25_0_0.rst
> +Significant Interface Changes
Remember we use sentence case for section headings per our Developer Guide and https://developers.google.com/style/highlights (look in all sections)

2023-07-24 19:17 UTC, jonathansick commented on releases/v25_0_0.rst
> +``obs.base.util.getInstrument`` will be replaced by ``lsst.pipe.base.Instrument.from_string``
One-sentence per line is preferred if possible (check all content).

2023-07-24 19:17 UTC, jonathansick commented on releases/v25_0_0.rst
> +--------------------------------------------
Check that section heading underlines are the same length as the section (check all headings).

2023-07-24 21:53 UTC, mwittgen commented
Fixes were made in DM-39813 and cherry-picked to this branch

2023-07-24 22:02 UTC, jonathansick approved these changes
Looks great.

2023-07-24 22:03 UTC, merged